config/routes.rb
Rails.application.routes.draw do
  resources :skate_parks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skate_park.rb
class SkatePark < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skate_parks_controller.rb
class SkateParksController < ApplicationController
  before_action :set_skate_park, only: %i[ show edit update destroy ]

  # GET /skate_parks or /skate_parks.json
  def index
    @skate_parks = SkatePark.all
  end

  # GET /skate_parks/1 or /skate_parks/1.json
  def show
  end

  # GET /skate_parks/new
  def new
    @skate_park = SkatePark.new
  end

  # GET /skate_parks/1/edit
  def edit
  end

  # POST /skate_parks or /skate_parks.json
  def create
    @skate_park = SkatePark.new(skate_park_params)

    respond_to do |format|
      if @skate_park.save
        format.html { redirect_to skate_park_url(@skate_park), notice: "Skate park was successfully created." }
        format.json { render :show, status: :created, location: @skate_park }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skate_park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skate_parks/1 or /skate_parks/1.json
  def update
    respond_to do |format|
      if @skate_park.update(skate_park_params)
        format.html { redirect_to skate_park_url(@skate_park), notice: "Skate park was successfully updated." }
        format.json { render :show, status: :ok, location: @skate_park }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skate_park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skate_parks/1 or /skate_parks/1.json
  def destroy
    @skate_park.destroy

    respond_to do |format|
      format.html { redirect_to skate_parks_url, notice: "Skate park was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skate_park
      @skate_park = SkatePark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skate_park_params
      params.require(:skate_park).permit(:title, :description, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skate_parks_helper.rb
module SkateParksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkateParkInMyCity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skate_parks/_form.html.erb
<%= form_with(model: skate_park) do |form| %>
  <% if skate_park.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skate_park.errors.count, "error") %> prohibited this skate_park from being saved:</h2>

      <ul>
        <% skate_park.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skate_parks/_skate_park.html.erb
<div id="<%= dom_id skate_park %>">
  <p>
    <strong>Title:</strong>
    <%= skate_park.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= skate_park.description %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= skate_park.text %>
  </p>

</div>

app/views/skate_parks/edit.html.erb
<h1>Editing skate park</h1>

<%= render "form", skate_park: @skate_park %>

<br>

<div>
  <%= link_to "Show this skate park", @skate_park %> |
  <%= link_to "Back to skate parks", skate_parks_path %>
</div>

app/views/skate_parks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Skate parks</h1>

<div id="skate_parks">
  <% @skate_parks.each do |skate_park| %>
    <%= render skate_park %>
    <p>
      <%= link_to "Show this skate park", skate_park %>
    </p>
  <% end %>
</div>

<%= link_to "New skate park", new_skate_park_path %>

app/views/skate_parks/new.html.erb
<h1>New skate park</h1>

<%= render "form", skate_park: @skate_park %>

<br>

<div>
  <%= link_to "Back to skate parks", skate_parks_path %>
</div>

app/views/skate_parks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skate_park %>

<div>
  <%= link_to "Edit this skate park", edit_skate_park_path(@skate_park) %> |
  <%= link_to "Back to skate parks", skate_parks_path %>

  <%= button_to "Destroy this skate park", @skate_park, method: :delete %>
</div>